dev:
  postgres:
    host: !ENV ${POSTGRES_HOST:localhost}
    port: !ENV ${POSTGRES_PORT:5432}
    user: !ENV ${POSTGRES_USER:postgres}
    password: !ENV ${POSTGRES_PASSWORD:postgres}
    database: !ENV ${POSTGRES_DATABASE:development}